### PR TITLE
Configurable samesite mode and cookie domain support

### PR DESCRIPTION
**Pull request by jaymeedwards**
Example logout mutation missing input field in README.

### CODE REVIEW

**Comment by jaymeedwards** [comment]
This is a set of changes I implemented for my site to work. I was only able to verify it in my situation, but here's what it does:

1. Adds a "Samesite mode" dropdown in the admin settings. It's set to "None" by default. I had to set it to "LAX" for CORS to work with my Apollo based app developing via http localhost. In the cloud (running in HTTPS) I set this to "None".

2. Adds a "Cookie domain" text field in the admin settings. By default cookies are created blank. Since I had my staging environment's wordpress at staging-wp.mysite.com and a remix front end app that hits it at staging.mysite.com, I had to set this value to the root domain starting with a period. This essentially says share it across subdomains. The nice thing is if you have separate dev/qa/prod environments and they all share subdomains, each environment has its own cookie hash so you don't have to worry about confusing sites with where you are and aren't logged in. But the browser will send all the cookies to each site in the subdomain.

3. The routine that determines if the HTTP origin is allowed needed to be tweaked. The response header has to be set to the origin of the request if it was in the allowed list. This wasn't working for me before.

4. There were a couple method calls that took parameters that weren't being used so I removed them. Hopefully most of this is self explanatory. Thanks for this great plugin, even if this PR never makes it in I'm just so happy to get this finally working for my use case!

**Comment by jaymeedwards** [comment]
I should mention there are two PRs I submitted to Jason Bahl over on the main wpgraphql repo that are required for this.

They fix a couple minor defects that prevented creating select (drop-down) configuration settings for wp-graphql plugins.

https://github.com/wp-graphql/wp-graphql/pull/2349
https://github.com/wp-graphql/wp-graphql/pull/2351

He hasn't released these yet but he did accept them.

**Comment by drewbaker** [comment]
@eavonius this is great thanks. Does this mean we have to wait for WP-GQL to be updated before we can accept this PR?

**Comment by jaymeedwards** [comment]
@drewbaker correct, he needs to do a release that includes those PRs before this one will work. I'm running a source version of wp-graphql in my site that has the fixes already which allows me to use the stuff in this PR now. Hopefully that happens soon!

**Comment by cfab** [comment]
Apparently wp-graphql merged eavonius PRs... 
oh no, just one of them..

**Comment by drewbaker** [comment]
@cfab thanks, merged now!

**Comment by cfab** [comment]
@drewbaker & @eavonius  Thank you. I've tested it, the set cookie attributes are indeed different in the returned header but unfortunately the cookie is still not set in the browser ( #37 ). Any idea ?

**Comment by drewbaker** [comment]
Can you give us some screenshots of the cookie results. The thing is, I don't use this plugin anymore so I'm leaning on community code fixes for it.

**Comment by cfab** [comment]
user test exists... 
1. I get a SUCCESS within response.
2. Then you have the headers with the 3 Set-Cookies
3. And then you can see that there is no cookie set at all. 
Am I missing something ?
Is there another way to do this ?
Thank you.

Capture d’écran 2022-06-07 à 10 55 00
Capture d’écran 2022-06-07 à 10 55 23
Capture d’écran 2022-06-07 à 10 55 47

**Comment by drewbaker** [comment]
The last screenshot is showing the cookies for localhost. But the cookies will on the GraphQL server (galpon?). 

The best way to test it, is login with the mutation, then just go to your WordPress dashboard. If you’re logged in you’ll be able to use it. I suspect it’s working based on your response headers.

**Comment by revnelson** [comment]
> The last screenshot is showing the cookies for localhost. But the cookies will on the GraphQL server (galpon?).
> 
> The best way to test it, is login with the mutation, then just go to your WordPress dashboard. If you’re logged in you’ll be able to use it. I suspect it’s working based on your response headers.

If this is the case, how can we make sure the user is logged in on the frontend after the user refreshes? It seems like we need the cookie to be set on the frontend so we can check for the cookie when authorizing on the frontend. I think we also need to send the cookie with future requests such as `query GetUser`. After getting "SUCCESS" with `loginWithCookies` a `user` query still returns `guest`.

**Comment by drewbaker** [comment]
This is not how cookies work in the browser. They are locked to the domain that set them, in this case the WordPress domain. It’s not possible to have them set (or read) for you frontend domain by WordPress (assuming they are on different domains).

Just because a cookie is present, doesn’t mean the user is authorized too by the way.

Your GraphQL client should allow you to send cookies with every request. Then WordPress will be logged in and WP-GQL will give you authorized data (drafts etc). 

See this for how we display WordPress edit header on our sites if the user is logged in. 
https://github.com/funkhaus/fuxt/blob/master/components/WpControls.vue

**Comment by revnelson** [comment]
> 
> Just because a cookie is present, doesn’t mean the user is authorized too by the way.
> 
Yes, I understand that. But using Svelte or Next I can have an api route that checks for the cookie and returns some sort of authorized status. If they are not truly authorized but just have the cookie, no queries or mutations that require authorization will work and upon failed response the cookie will be removed.

> Your GraphQL client should allow you to send cookies with every request. Then WordPress will be logged in and WP-GQL will give you authorized data (drafts etc).
> 
Currently logging in seems to be working and I can see the "set-cookies" header on response. However, sending a query for `user` still shows guest. If the cookie is working, it should show the user, right?

**Comment by revnelson** [comment]
Nevermind, please disregard my comments. This plugin is working fine, I was just having issues with running my dev as `http://localhost:3000`. Once I properly set up something like `https://local.example.com`, I can now see the cookies are set and querying `viewer` is working as an auth check.

**Comment by cfab** [comment]
> The last screenshot is showing the cookies for localhost. But the cookies will on the GraphQL server (galpon?).
> 
> The best way to test it, is login with the mutation, then just go to your WordPress dashboard. If you’re logged in you’ll be able to use it. I suspect it’s working based on your response headers.

Thank you very much.

**Comment by kidunot89** [comment]
@eavonius 🔥 Excellent work on this.

**Pull request merged**
