### PR TITLE
Add composer configuration

### PR DESCRIPTION
**Pull request by fedek6**
Hi,
I've added a `composer.json` file. This way I can use your plugin with PHP composer.  

Thanks!

### CODE REVIEW

**Comment by jeysaravana** [comment]
@drewbaker could you please merge this?

**Comment by jeysaravana** [comment]
@drewbaker thanks for the quick turn around, could you please also update the plugin version number and make a new release https://github.com/funkhaus/wp-graphql-cors/releases?
It hasn't been updated the plugin version number and release.
thanks

**Comment by drewbaker** [comment]
@jeysaravana done!

**Comment by revnelson** [comment]
Can you add some info for how we can use this in our composer.json files? Is this uploaded to a repository?

**Comment by drewbaker** [comment]
@revnelson does this help: https://www.daggerhartlab.com/composer-how-to-use-git-repositories/

**Comment by fedek6** [comment]
@revnelson an example from me (it has priority over Packagist):
```
{
  "minimum-stability": "dev",
  "prefer-stable": true,
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/fedek6/PHPExcel"
    }
  ],
  "require": {
    "phpoffice/phpexcel": "dev-main"
  }
}
```

**Pull request merged**
